routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/post', 'PostsController@index')->name('post.index');
Route::get('/post/create', 'PostsController@create')->name('post.create')->middleware('role:writer|admin');
Route::post('/post', 'PostsController@store')->name('post.store');
Route::get('/post/{post}', 'PostsController@show')->name('post.show');
Route::put('/post/{post}', 'PostsController@update')->name('post.update');
Route::delete('/post/{post}', 'PostsController@destroy')->name('post.destroy');
Route::get('/post/{post}/edit', 'PostsController@edit')->name('post.edit')->middleware('permission:edit post');

Route::resource('/products', 'ProductsController');
Route::get('/all-products', 'ProductsController@getAllProducts');
Route::post('/product/store', 'ProductsController@store');
Route::post('/product/update/{product}', 'ProductsController@update');
Route::post('/product/destroy/{product}', 'ProductsController@destroy');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = "products";
    protected  $fillable = [
        'name',
        'price',
        'description',
    ];
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Product;
use Illuminate\Support\Facades\Log;

class ProductsController extends Controller
{
    protected $Product;
    public function __construct( Product $Product )
    {
        $this->Product = $Product;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('products.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $save_product  = $this->Product->Create( $request->all() );

        if( $save_product ){
           return [
               'status' => 'success',
               'message'=>'Product has been successfully saved!'
           ];
        }else{
            return [
                'status' => 'fail',
                'message'=>'Product fail to save!'
            ];
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['product'] = $this->Product->where( 'id', $id )->first();
        return view('products.edit', $data );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        //Log::info( $request->all() );

        $product = $this->Product->where('id', $id)->first();
        $update =  $product->update( $request->all() );

        if( $update ){
            return [
                'status' => 'success',
                'message'=>'Product has been successfully update!'
            ];
        }else{
            return [
                'status' => 'fail',
                'message'=>'Product fail to update!'
            ];
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product =  $this->Product->where('id', $id)->first();
        $delete =  $product->delete();

        if( $delete ){
            return [
                'status' => 'success',
                'message'=>'Product has been successfully update!'
            ];
        }else{
            return [
                'status' => 'fail',
                'message'=>'Product fail to update!'
            ];
        }
    }

    function getAllProducts(){
        $products = $this->Product->orderBy('id', 'DESC' )->get()->toArray();

        return $products;
    }
}

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
    <div id="root" class="container" xmlns="http://www.w3.org/1999/html">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">

                    <div class="card-header">
                        Product create
                        <a class="float-right" href="{{ route('products.create') }}">Add new</a>
                    </div>

                    <p v-for="product in products">adf asdf asdf</p>


                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        @include('includes.flash_msg')
                        <form method="post" action="{{ route('products.store') }}">
                            @csrf
                            <div class="form-group">
                                <label>Name</label>
                                <input type="text" name="name" class="form-control"/>
                            </div>
                            <div class="form-group">
                                <label>Price</label>
                                <input type="text" name="price" class="form-control"/>
                            </div>
                            <div class="form-group">
                                <label>Description</label>
                                <textarea class="form-control" name="description" rows="6"> </textarea>
                            </div>

                            <div class="form-group text-right">
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{ asset('vue/vue.js') }}"></script>
    <script src="{{ asset('axios/axios.js') }}"></script>
    <script type="text/javascript">var home_url="{{ url('/') }}"</script>

    <script type="text/javascript">
        var App = new Vue({
            el: "#root",
            data: {
                products:[]
            },

            mounted(){
                this.getAllProducts();
            },

            methods:{
                getAllProducts(){
                    //currentApp = this;
                    axios.get(home_url + '/all-products')
                        .then(response => {
                            App.products = response.data
                            console.log(App.products)
                        })
                }
            }

        })
    </script>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
<div id="root" class="container" xmlns="http://www.w3.org/1999/html">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">

                <div class="card-header">
                    Product create
                    <a class="float-right" href="{{ route('products.create') }}">Add new</a>
                </div>



                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    @include('includes.flash_msg')
                        {{--<div class="alert alert-primary alert-dismissible fade show" role="alert">
                            This is a primary alert—check it out!
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="alert alert-secondary alert-dismissible fade show" role="alert">
                            This is a secondary alert—check it out!
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                            This is a warning alert—check it out!
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="alert alert-info alert-dismissible fade show" role="alert">
                            This is a info alert—check it out!
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="alert alert-light alert-dismissible fade show" role="alert">
                            This is a light alert—check it out!
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="alert alert-dark alert-dismissible fade show" role="alert">
                            This is a dark alert—check it out!
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>--}}

                        <form method="post" action="{{ route('products.update', $product['id'] ) }}">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label>Name</label>
                                <input type="text" value="{{ $product['name'] }}" name="name" class="form-control"/>
                            </div>
                            <div class="form-group">
                                <label>Price</label>
                                <input type="text" value="{{ $product['price'] }}" name="price" class="form-control"/>
                            </div>
                            <div class="form-group">
                                <label>Description</label>
                                <textarea class="form-control" name="description" rows="6"> {{ $product['description'] }} </textarea>
                            </div>

                            <div class="form-group text-right">
                                <button type="submit" class="btn btn-primary">Update</button>
                            </div>

                        </form>

                </div>
            </div>
        </div>
    </div>
</div>



@endsection

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')

    <div id="root">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="card">
                        <div class="card-header">
                            Products
                            <button @click="showingAddSection = true;" class="float-right btn btn-primary" >Add new</button>
                        </div>
                        <div class="card-body">
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif
                            <table class="table">
                                <thead>
                                <tr>
                                    <td>#SL</td>
                                    <td>Name</td>
                                    <td>Price</td>
                                    <td>Action</td>
                                </tr>
                                </thead>

                                <tbody>

                                <tr v-for='( product, index ) in products'>
                                    <td> @{{ index+1 }}</td>
                                    <td> @{{ product.name }}</td>
                                    <td> @{{ product.price }}</td>
                                    <td>
                                        {{--<a href="{{ route('products.edit', $product['id']) }}">Edit</a>--}}

                                        <button class="btn btn-primary btn-sm" @click="showingEditSection = true; selectProduct(product)"><i class="fa fa-pencil-square-o"></i></button>
                                        <button class ="btn btn-danger btn-sm" @click="showingDeleteSection = true; selectProduct(product)"><i class="fa fa-trash-o"></i></button>
                                    </td>
                                </tr>

                                </tbody>

                            </table>
                        </div>
                    </div>
                </div>

                <div class="col-sm-6">
                    <div class="card" id="addSec" v-if="showingAddSection">
                        <div class="card-header">
                            Product create
                            <button @click="showingAddSection = false;" type="button" class="close">
                                <span>&times;</span>
                            </button>
                        </div>
                        <div class="card-body">

                            <div class="form-group">
                                <label>Name</label>
                                <input type="text" name="" v-model="newProduct.name" class="form-control"/>
                            </div>
                            <div class="form-group">
                                <label>Price</label>
                                <input type="text" name="" v-model="newProduct.price" class="form-control"/>
                            </div>
                            <div class="form-group">
                                <label>Description</label>
                                <textarea class="form-control" name="" v-model="newProduct.description"  rows="4"> </textarea>
                            </div>

                            <div class="form-group text-right">
                                <button type="button" @click="saveProduct" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                    </div>

                    <div class="card" id="editSec" v-if="showingEditSection">
                        <div class="card-header">
                            Product edit
                            <button @click="showingEditSection = false;" type="button" class="close">
                                <span>&times;</span>
                            </button>
                        </div>
                        <div class="card-body">

                            <div class="form-group">
                                <label>Name</label>
                                <input type="text" name="" v-model="clickedProduct.name" class="form-control"/>
                            </div>
                            <div class="form-group">
                                <label>Price</label>
                                <input type="text" name="" v-model="clickedProduct.price" class="form-control"/>
                            </div>
                            <div class="form-group">
                                <label>Description</label>
                                <textarea class="form-control" name="" v-model="clickedProduct.description"  rows="4"> </textarea>
                            </div>

                            <div class="form-group text-right">
                                <button type="button" @click="updateProduct" class="btn btn-primary">Update</button>
                            </div>
                        </div>
                    </div>

                    <div class="card" id="deleteSec" v-if="showingDeleteSection">
                        <div class="card-header">
                            Product delete
                            <button type="button" class="close" @click="showingDeleteSection = false;">
                                <span>&times;</span>
                            </button>
                        </div>

                        <div class="card-body">
                            <h5>Are you sure delete @{{clickedProduct.name}}!</h5>

                            <div class="form-group text-right">
                                <button class="btn btn-primary" @click="showingDeleteSection = false;">No</button>
                                <button class="btn btn-danger" @click="showingDeleteSection = false; deleteProduct()">Yes</button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>


<script src="{{ asset('vue/vue.js') }}"></script>
<script src="{{ asset('axios/axios.js') }}"></script>
<script type="text/javascript">var home_url="{{ url('/') }}"</script>

<script type="text/javascript">
    var App = new Vue({
        el: "#root",
        data: {
            showingAddSection: false,
            showingEditSection: false,
            showingDeleteSection: false,
            products:[],
            newProduct: {name: "", price: "", description: ""},
            clickedProduct: {}
        },

        mounted(){
            this.getAllProducts();
        },

        methods:{
            getAllProducts(){
                //currentApp = this;
                axios.get(home_url + '/all-products')
                    .then(response => {
                        App.products = response.data
                        //console.log(App.products)
                    })
            },

            saveProduct() {
                currentApp = this;
                axios.post(home_url + '/product/store', this.newProduct)
                    .then(response => {
                        console.log(response.data.status)
                        if( response.data.status == "success"){
                            this.getAllProducts();
                            currentApp.newProduct = {name: "", price: "", description: ""};
                        }
                    })
            },

            selectProduct( product ){
                currentApp = this;
                currentApp.clickedProduct = product;
            },
            updateProduct() {
                currentApp = this;
                axios.post(home_url + '/product/update/'+currentApp.clickedProduct.id, currentApp.clickedProduct)
                    .then(response => {
                        console.log(response.data.status);
                        if( response.data.status == "success"){
                            this.getAllProducts();
                            currentApp.clickedProduct = {name: "", price: "", description: ""};
                        }
                    })
            },

            deleteProduct() {
                currentApp = this;
                //alert(currentApp.clickedProduct.id);
                axios.post(home_url + '/product/destroy/'+currentApp.clickedProduct.id)
                    .then(response => {
                        console.log(response.data.status);
                        if( response.data.status == "success"){
                            this.getAllProducts();
                           
                        }
                    })
            }
        },




    })
</script>


@endsection